---
- name: Initial Setup
  hosts: Palo_Alto
  connection: local
  gather_facts: false
  environment:
     GIT_SSL_NO_VERIFY: 'true'

  tasks:

  - name: Set DNS
    panos_mgtconfig:
      ip_address: "{{private_ip}}"
      api_key: "{{api_key}}"
      dns_server_primary: "{{dns_server_primary}}"
      dns_server_secondary: "{{dns_server_secondary}}"

  - name: Configure Interface
    panos_interface:
      api_key: "{{api_key}}"
      ip_address: "{{private_ip}}"
      ip: "{{interface_ip}}"
      if_name: "ethernet1/1"
      zone_name: "{{zone}}"

#https://github.com/PaloAltoNetworks/ansible-pan/blob/master/examples/fw_interface.yml