---
# tasks file for F5-BIG-IQ

- name: COLLECT BIG-IP FACTS
  bigip_facts:
    include: system_info
    server: "{{private_ip}}"
    user: "{{ansible_user}}"
    password: "{{ansible_ssh_pass}}"
    server_port: 8443
  register: bigip_facts

- name: COMPLETE BIG-IP SYSTEM INFORMATION
  debug:
    var: bigip_facts