---
- name: AFIRME-LAB-SETUP
  hosts: AFIRME-LAB 
  connection: local
  gather_facts: false
  
  tasks:

  - name: Set the DNS settings on the BIG-IP-1
    bigip_device_dns:
      name_servers: "{{name_servers}}"
      server: "{{f5_1_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      validate_certs: no
      state: present

  - name: Set the DNS settings on the BIG-IP-3
    bigip_device_dns:
      name_servers: "{{name_servers}}"
      server: "{{f5_3_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      validate_certs: no
      state: present

  - name: Set NTP server-1
    bigip_device_ntp:
      ntp_servers: "{{ntp_servers}}"
      server: "{{f5_1_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      validate_certs: no
      state: present

  - name: Set NTP server-3
    bigip_device_ntp:
      ntp_servers: "{{ntp_servers}}"
      server: "{{f5_3_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      validate_certs: no
      state: present

  - name: Set timezone-1
    bigip_device_ntp:
      timezone: America/Mexico_City
      server: "{{f5_1_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      validate_certs: no
      state: present

  - name: Set timezone-3
    bigip_device_ntp:
      timezone: America/Mexico_City
      server: "{{f5_3_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      validate_certs: no
      state: present

  - name: CREATE NODES - F5-1
    bigip_node:
      server: "{{f5_1_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: "443"
      host: "{{item}}"
      name: "{{hostvars[item].name}}"
      validate_certs: "no"
    loop: "{{groups['webservers']}}"

  - name: CREATE NODES - F5-3
    bigip_node:
      server: "{{f5_3_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: "443"
      host: "{{item}}"
      name: "{{hostvars[item].name}}"
      validate_certs: "no"
    loop: "{{groups['webservers']}}"

  - name: CREATE POOL-1
    bigip_pool:
      server: "{{f5_1_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: "443"
      name: "http_pool"
      lb_method: "round-robin"
      monitors: "/Common/http"
      monitor_type: "and_list"
      validate_certs: "no"

  - name: CREATE POOL-3
    bigip_pool:
      server: "{{f5_1_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: "443"
      name: "http_pool"
      lb_method: "round-robin"
      monitors: "/Common/http"
      monitor_type: "and_list"
      validate_certs: "no"

  - name: ADD POOL MEMBERS F5-1
    bigip_pool_member:
      server: "{{f5_1_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: "443"
      state: present
      host: "{{item}}"
      name: "{{hostvars[item].name}}"
      port: "80"
      pool: "http_pool"
      validate_certs: "no"
    loop: "{{groups['webservers']}}"

  - name: ADD POOL MEMBERS F5-3
    bigip_pool_member:
      server: "{{f5_3_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: "443"
      state: present
      host: "{{item}}"
      name: "{{hostvars[item].name}}"
      port: "80"
      pool: "http_pool"
      validate_certs: "no"
    loop: "{{groups['webservers']}}"
    

  - name: ADD VIRTUAL SERVER-1
    bigip_virtual_server:
      server: "{{f5_1_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: "443"
      name: "http-virtualserver"
      destination: "{{f5_1_http_ip}}"
      port: "80"
      enabled_vlans: "all"
      all_profiles: ['http','clientssl','oneconnect']
      pool: "http_pool"
      snat: "Automap"
      validate_certs: "no"

  - name: ADD VIRTUAL SERVER-3
    bigip_virtual_server:
      server: "{{f5_3_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: "443"
      name: "http-virtualserver"
      destination: "{{f5_3_http_ip}}"
      port: "80"
      enabled_vlans: "all"
      all_profiles: ['http','clientssl','oneconnect']
      pool: "http_pool"
      snat: "Automap"
      validate_certs: "no"

